const $=id=>document.getElementById(id);
const KEY='cpsu_eventhub_v2';
const initial={events:[{id:101,name:'CPSU Foundation Day',organizer:'Office of Student Affairs',date:'2026-10-15',time:'08:00',venue:'CPSU Main Campus',capacity:200,status:'Open',details:'University-wide celebration and student activities.'},{id:102,name:'IT Skills and Innovation Seminar',organizer:'College of Information Technology',date:'2026-10-24',time:'09:00',venue:'ICT Laboratory',capacity:80,status:'Open',details:'Technology talks, demonstrations, and practical sessions.'},{id:103,name:'Intramurals 2026',organizer:'Sports Office',date:'2026-11-05',time:'08:00',venue:'CPSU Gymnasium',capacity:300,status:'Open',details:'Annual sports and team-building activities.'}],students:[{id:'2026-001',name:'Juan Dela Cruz',course:'BSIT 1-C',email:'juan@cpsu.edu.ph'},{id:'2026-002',name:'Maria Santos',course:'BSIT 1-C',email:'maria@cpsu.edu.ph'},{id:'2026-003',name:'Pedro Reyes',course:'BSCS 1-A',email:'pedro@cpsu.edu.ph'}],registrations:[],queue:[],history:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||initial;let events=data.events,students=data.students,registrations=data.registrations,queue=data.queue,history=data.history;let nextEvent=Math.max(100,...events.map(e=>e.id))+1,nextReg=Math.max(0,...registrations.concat(queue).map(r=>r.id||0))+1;
function persist(){localStorage.setItem(KEY,JSON.stringify({events,students,registrations,queue,history}))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function log(x){history.push(new Date().toLocaleTimeString()+' — '+x);if(history.length>30)history.shift()}
function dateFmt(d){return d?new Date(d+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'-'}
function eventById(id){return events.find(e=>e.id===Number(id))}
function studentById(id){return students.find(s=>s.id.toLowerCase()===String(id).toLowerCase())}
function countForEvent(id){return registrations.filter(r=>r.eventId===id).length+queue.filter(r=>r.eventId===id).length}
function mergeSort(arr,key){if(arr.length<=1)return arr.slice();let m=Math.floor(arr.length/2),l=mergeSort(arr.slice(0,m),key),r=mergeSort(arr.slice(m),key),o=[];while(l.length&&r.length)o.push(String(l[0][key]).localeCompare(String(r[0][key]))<=0?l.shift():r.shift());return o.concat(l,r)}
function binarySearch(arr,target){let lo=0,hi=arr.length-1,target2=target.toLowerCase();while(lo<=hi){let mid=Math.floor((lo+hi)/2),v=arr[mid].id.toLowerCase();if(v===target2)return arr[mid];v<target2?lo=mid+1:hi=mid-1}return null}
function hashId(id,size=7){let h=0;for(const c of id)h=(h*31+c.charCodeAt(0))>>>0;return h%size}
class BSTNode{constructor(v){this.v=v;this.left=null;this.right=null}}
class BST{constructor(){this.root=null}insert(v){this.root=this._i(this.root,v)}_i(n,v){if(!n)return new BSTNode(v);v<n.v?n.left=this._i(n.left,v):v>n.v&&(n.right=this._i(n.right,v));return n}search(v){let n=this.root;while(n){if(n.v===v)return n;n=v<n.v?n.left:n.right}return null}inorder(n=this.root,a=[]){if(!n)return a;this.inorder(n.left,a);a.push(n.v);this.inorder(n.right,a);return a}}
function eventBST(){let b=new BST;events.forEach(e=>b.insert(e.id));return b}
function renderEventSelect(id){const els=events.filter(e=>e.status==='Open'&&countForEvent(e.id)<e.capacity);const html='<option value="">Select an open event</option>'+els.map(e=>`<option value="${e.id}">${esc(e.name)} — ${dateFmt(e.date)}</option>`).join('');['qEvent'].forEach(x=>{if($(x)){let old=$(x).value;$(x).innerHTML=html;if([...$(x).options].some(o=>o.value===old))$(x).value=old}})}
function render(){renderStats();renderUpcoming();renderEvents();renderStudents();renderRegs();renderQueue();renderHistory();renderDSA();renderEventSelect();persist()}
function renderStats(){$('totalEvents').textContent=events.length;$('openEvents').textContent=events.filter(e=>e.status==='Open').length;$('totalStudents').textContent=students.length;$('pending').textContent=queue.length}
function renderUpcoming(){let list=events.filter(e=>e.status==='Open').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,4);$('upcoming').innerHTML=list.map(e=>`<div class="event-card"><div><span class="status open">OPEN</span><h3>${esc(e.name)}</h3><p>${dateFmt(e.date)} • ${esc(e.time)} • ${esc(e.venue)}</p><small>${Math.max(0,e.capacity-countForEvent(e.id))} slots left</small></div><button onclick="quickFill(${e.id})">Register</button></div>`).join('')||'<p>No upcoming open events.</p>'}
function renderEvents(){let q=($('search')?.value||'').trim().toLowerCase(),list=events.filter(e=>Object.values(e).join(' ').toLowerCase().includes(q));let mode=$('sort')?.value||'date';if(mode==='name')list=mergeSort(list,'name');else if(mode==='capacity')list=mergeSort(list,'capacity');else if(mode==='status')list=mergeSort(list,'status');else list=mergeSort(list,'date');$('rows').innerHTML=list.map(e=>{let rem=Math.max(0,e.capacity-countForEvent(e.id));return `<tr><td>#${e.id}</td><td><strong>${esc(e.name)}</strong><br><small>${esc(e.details)}</small></td><td>${dateFmt(e.date)}<br>${esc(e.time)}</td><td>${esc(e.venue)}</td><td>${esc(e.organizer)}</td><td>${rem}/${e.capacity}</td><td><span class="status ${e.status.toLowerCase()}">${e.status}</span></td><td><button onclick="editEvent(${e.id})">Edit</button> <button class="danger" onclick="deleteEvent(${e.id})">Delete</button></td></tr>`}).join('')||'<tr><td colspan="8">No events found.</td></tr>'}
function renderStudents(){let list=mergeSort(students,'id');$('studentRows').innerHTML=list.map(s=>`<tr><td><strong>${esc(s.id)}</strong></td><td>${esc(s.name)}</td><td>${esc(s.course)}</td><td>${esc(s.email)}</td><td>${registrations.filter(r=>r.studentId===s.id).length}</td><td><button class="danger" onclick="deleteStudent('${esc(s.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No students.</td></tr>'}
function renderRegs(){let q=($('regSearch')?.value||'').toLowerCase(),list=registrations.filter(r=>(r.studentName+' '+r.studentId+' '+(eventById(r.eventId)?.name||'')).toLowerCase().includes(q));$('regRows').innerHTML=list.slice().reverse().map(r=>`<tr><td>#${r.id}</td><td>${esc(r.studentName)}</td><td>${esc(r.studentId)}</td><td>${esc(eventById(r.eventId)?.name||'Removed')}</td><td>${new Date(r.registeredAt).toLocaleString()}</td><td><button class="danger" onclick="cancelReg(${r.id})">Cancel</button></td></tr>`).join('')||'<tr><td colspan="6">No completed registrations.</td></tr>'}
function renderQueue(){$('queueText').innerHTML=queue.map((r,i)=>`<div class="queue-item"><strong>${i+1}. ${esc(r.studentName)}</strong><span>${esc(r.studentId)} • ${esc(r.course)}</span><small>${esc(eventById(r.eventId)?.name||'Event removed')}</small></div>`).join('')||'<p>No pending registrations.</p>'}
function renderHistory(){$('history').innerHTML=history.slice().reverse().map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No actions yet.</li>'}
function renderDSA(){let q=queue.slice(0,8);$('queueViz').innerHTML=q.map(r=>`<span class="node">${esc(r.studentName)}</span>`).join('<b>→</b>')||'<span class="muted">Queue empty</span>';let st=history.slice(-5).reverse();$('stackViz').innerHTML=st.map(x=>`<span class="stack-node">${esc(x.split(' — ')[1]||x)}</span>`).join('')||'<span class="muted">Stack empty</span>';let buckets=Array.from({length:7},()=>[]);students.forEach(s=>buckets[hashId(s.id)].push(s.id));$('hashViz').innerHTML=buckets.map((b,i)=>`<div><b>${i}</b><span>${b.map(esc).join(', ')||'empty'}</span></div>`).join('');let b=eventBST();$('bstViz').innerHTML=b.inorder().map(id=>`<span class="node">#${id}</span>`).join(' → ')||'Empty'}
function quickFill(id){document.querySelector('[data-view="dashboard"]').click();$('qEvent').value=id;$('qName').focus()}
function editEvent(id){let e=eventById(id);if(!e)return;document.querySelector('[data-view="events"]').click();$('eventId').value=e.id;$('eventName').value=e.name;$('organizer').value=e.organizer;$('eventDate').value=e.date;$('eventTime').value=e.time;$('venue').value=e.venue;$('capacity').value=e.capacity;$('eventStatus').value=e.status;$('eventDetails').value=e.details;window.scrollTo({top:0,behavior:'smooth'})}
function deleteEvent(id){let e=eventById(id);if(registrations.some(r=>r.eventId===id)||queue.some(r=>r.eventId===id)){alert('This event has registrations. Close or complete it instead of deleting it.');return}events=events.filter(x=>x.id!==id);log(`Deleted event #${id} (${e.name})`);render()}
function deleteStudent(id){if(registrations.some(r=>r.studentId===id)||queue.some(r=>r.studentId===id)){alert('This student has registration activity and cannot be deleted.');return}students=students.filter(s=>s.id!==id);log(`Deleted student ${id}`);render()}
function cancelReg(id){let i=registrations.findIndex(r=>r.id===id);if(i<0)return;let r=registrations[i];registrations.splice(i,1);log(`Cancelled registration #${id} for ${r.studentName}`);render()}
function submitRegistration(name,id,course,eventId,email){name=name.trim();id=id.trim();course=course.trim();let ev=eventById(eventId);if(!name||!id||!course||!ev)return alert('Complete all required registration fields.');let s=studentById(id);if(!s){if(!email||!email.includes('@'))return alert('A valid school email is required for a new student.');students.push({id,name,course,email});log(`Added student ${id} to hash table`)}else if(s.name.toLowerCase()!==name.toLowerCase()||s.course.toLowerCase()!==course.toLowerCase())return alert('Student ID already belongs to another student record.');if(registrations.some(r=>r.studentId.toLowerCase()===id.toLowerCase()&&r.eventId===eventId)||queue.some(r=>r.studentId.toLowerCase()===id.toLowerCase()&&r.eventId===eventId))return alert('Duplicate registration detected.');if(countForEvent(eventId)>=ev.capacity)return alert('This event is full.');let r={id:nextReg++,studentName:name,studentId:id,course,eventId,email:s?.email||email,registeredAt:new Date().toISOString()};queue.push(r);log(`Enqueued registration #${r.id} for ${name}`);return true}
$('eventForm').onsubmit=e=>{e.preventDefault();let id=Number($('eventId').value),d={id:id||nextEvent++,name:$('eventName').value.trim(),organizer:$('organizer').value.trim(),date:$('eventDate').value,time:$('eventTime').value,venue:$('venue').value.trim(),capacity:Number($('capacity').value),status:$('eventStatus').value,details:$('eventDetails').value.trim()};if(!d.name||!d.organizer||!d.date||!d.time||!d.venue||!d.details||d.capacity<1)return alert('Complete all event fields.');if(id){let i=events.findIndex(x=>x.id===id);events[i]=d;log(`Updated event #${id}`)}else{events.push(d);log(`Added event #${d.id} (${d.name})`)}$('eventForm').reset();$('eventId').value='';render()};
$('studentForm').onsubmit=e=>{e.preventDefault();let id=$('studentId').value.trim();if(studentById(id))return alert('Student ID already exists.');students.push({id,name:$('studentName').value.trim(),course:$('course').value.trim(),email:$('studentEmail').value.trim()});log(`Inserted student ${id} into hash table`);e.target.reset();render()};
$('quickReg').onsubmit=e=>{e.preventDefault();if(submitRegistration($('qName').value,$('qId').value,$('qCourse').value,$('qEvent').value,'')){e.target.reset();render()}};
$('process').onclick=()=>{if(!queue.length)return alert('Registration queue is empty.');let r=queue.shift(),ev=eventById(r.eventId);registrations.push(r);log(`Dequeued and processed registration #${r.id} — ${r.studentName} for ${ev?.name||'Event'}`);render()};
$('undo').onclick=()=>{if(!history.length)return alert('Stack is empty.');let x=history.pop();alert('Popped: '+x);render()};$('cancel').onclick=()=>{$('eventForm').reset();$('eventId').value=''};$('sort').onchange=render;$('searchBtn').onclick=render;$('reset').onclick=()=>{$('search').value='';render()};$('studentSearch').onkeydown=e=>{if(e.key==='Enter')$('findStudent').click()};$('findStudent').onclick=()=>{let a=mergeSort(students,'id'),s=binarySearch(a,$('studentSearch').value.trim());alert(s?`Binary Search found:\n${s.id} — ${s.name}\n${s.course}`:'Student ID not found.');};$('regSearch').oninput=render;$('theme').onclick=()=>{document.body.classList.toggle('dark');$('theme').textContent=document.body.classList.contains('dark')?'☀️ Light':'🌙 Dark'};$('clearData').onclick=()=>{if(confirm('Reset all demo data?')){localStorage.removeItem(KEY);location.reload()}};
$('exportCsv').onclick=()=>{let lines=[['Registration ID','Student ID','Student Name','Course','Event','Date'].join(',')].concat(registrations.map(r=>[r.id,r.studentId,r.studentName,r.course,eventById(r.eventId)?.name||'',r.registeredAt].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')));let blob=new Blob([lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cpsu-registrations.csv';a.click();URL.revokeObjectURL(a.href)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');render()});
if(!history.length)log('Initialized CPSU EventHub demo data');render();
